const Data = [
    {
                    pabellon: 1,
                    cama:'A66',
                    ingreso: 'Urgencias',
                    tipoDocumento: 'C.C',
                    documento:1094893772,
                    folio:12,
                    paciente:"Diego Lopez", 
                    fechaIngreso:"24-08-2024", 
                    origenAtencion:'Dolor',
                    tipoConcepto:'Dolor',
                    cups:'3277',
                    nombreProcedimiento:'Urgencias',
                    cantidad: 10,
                    fechaOrden: '24-08-2024',
                    observaciones: 'Datos de observacion'
                },
                {
                    
                    pabellon: 10,
                    cama:'C12',
                    ingreso: 'Urgencias',
                    tipoDocumento: 'T.I',
                    documento:109833256,
                    folio:18,
                    paciente:"Paula andrea", 
                    fechaIngreso:"24-08-2024", 
                    origenAtencion:'Dolor',
                    tipoConcepto:'Dolor',
                    cups:'122',
                    nombreProcedimiento:'Urgencias',
                    cantidad: 7,
                    fechaOrden: '24-08-2024',
                    observaciones: 'Datos de observacion'
                },
                {
                    
                    pabellon: 10,
                    cama:'A66',
                    ingreso: 'Urgencias',
                    tipoDocumento: 'C.C.',
                    documento:109856334,
                    folio:6,
                    paciente:"Edwin Carvajal", 
                    fechaIngreso:"24-08-2024", 
                    origenAtencion:'Dolor',
                    tipoConcepto:'Dolor',
                    cups:'3277',
                    nombreProcedimiento:'Urgencias',
                    cantidad: 10,
                    fechaOrden: '24-08-2024',
                    observaciones: 'Datos de observacion'
                },
                {
                    
                    pabellon: 7,
                    cama:'A66',
                    ingreso: 'Urgencias',
                    tipoDocumento: 'C.C.',
                    documento:4115662,
                    folio:18,
                    paciente:"Andrea Gusman", 
                    fechaIngreso:"24-08-2024", 
                    origenAtencion:'Dolor',
                    tipoConcepto:'Dolor',
                    cups:'3277',
                    nombreProcedimiento:'Urgencias',
                    cantidad: 10,
                    fechaOrden: '24-08-2024',
                    observaciones: 'Datos de observacion'
                },
                {
                    
                    pabellon: 10,
                    cama:'A66',
                    ingreso: 'Urgencias',
                    tipoDocumento: 'C.C.',
                    documento:109833256,
                    folio:18,
                    paciente:"Diego Lopez", 
                    fechaIngreso:"24-08-2024", 
                    origenAtencion:'Dolor',
                    tipoConcepto:'Dolor',
                    cups:'3277',
                    nombreProcedimiento:'Urgencias',
                    cantidad: 10,
                    fechaOrden: '24-08-2024',
                    observaciones: 'Datos de observacion'
                },
                {
                    
                    pabellon: 10,
                    cama:'A66',
                    ingreso: 'Urgencias',
                    tipoDocumento: 'C.C.',
                    documento:109833256,
                    folio:18,
                    paciente:"Diego Lopez", 
                    fechaIngreso:"24-08-2024", 
                    origenAtencion:'Dolor',
                    tipoConcepto:'Dolor',
                    cups:'3277',
                    nombreProcedimiento:'Urgencias',
                    cantidad: 10,
                    fechaOrden: '24-08-2024',
                    observaciones: 'Datos de observacion'
                },
                {
                    
                    pabellon: 10,
                    cama:'A66',
                    ingreso: 'Urgencias',
                    tipoDocumento: 'C.C.',
                    documento:109833256,
                    folio:18,
                    paciente:"Diego Lopez", 
                    fechaIngreso:"24-08-2024", 
                    origenAtencion:'Dolor',
                    tipoConcepto:'Dolor',
                    cups:'3277',
                    nombreProcedimiento:'Urgencias',
                    cantidad: 10,
                    fechaOrden: '24-08-2024',
                    observaciones: 'Datos de observacion'
                },
                {
                    
                    pabellon: 10,
                    cama:'A66',
                    ingreso: 'Urgencias',
                    tipoDocumento: 'C.C.',
                    documento:109833256,
                    folio:18,
                    paciente:"Diego Lopez", 
                    fechaIngreso:"24-08-2024", 
                    origenAtencion:'Dolor',
                    tipoConcepto:'Dolor',
                    cups:'3277',
                    nombreProcedimiento:'Urgencias',
                    cantidad: 10,
                    fechaOrden: '24-08-2024',
                    observaciones: 'Datos de observacion'
                },
                {
                    
                    pabellon: 10,
                    cama:'A66',
                    ingreso: 'Urgencias',
                    tipoDocumento: 'C.C.',
                    documento:109833256,
                    folio:18,
                    paciente:"Diego Lopez", 
                    fechaIngreso:"24-08-2024", 
                    origenAtencion:'Dolor',
                    tipoConcepto:'Dolor',
                    cups:'3277',
                    nombreProcedimiento:'Urgencias',
                    cantidad: 10,
                    fechaOrden: '24-08-2024',
                    observaciones: 'Datos de observacion'
                },
                {
                    
                    pabellon: 10,
                    cama:'A66',
                    ingreso: 'Urgencias',
                    tipoDocumento: 'C.C.',
                    documento:109833256,
                    folio:18,
                    paciente:"Diego Lopez", 
                    fechaIngreso:"24-08-2024", 
                    origenAtencion:'Dolor',
                    tipoConcepto:'Dolor',
                    cups:'3277',
                    nombreProcedimiento:'Urgencias',
                    cantidad: 10,
                    fechaOrden: '24-08-2024',
                    observaciones: 'Datos de observacion'
                },
                {
                    
                    pabellon: 10,
                    cama:'A66',
                    ingreso: 'Urgencias',
                    tipoDocumento: 'C.C.',
                    documento:109833256,
                    folio:18,
                    paciente:"Diego Lopez", 
                    fechaIngreso:"24-08-2024", 
                    origenAtencion:'Dolor',
                    tipoConcepto:'Dolor',
                    cups:'3277',
                    nombreProcedimiento:'Urgencias',
                    cantidad: 10,
                    fechaOrden: '24-08-2024',
                    observaciones: 'Datos de observacion'
                },
                {
                    
                    pabellon: 10,
                    cama:'A66',
                    ingreso: 'Urgencias',
                    tipoDocumento: 'C.C.',
                    documento:109833256,
                    folio:18,
                    paciente:"Diego Lopez", 
                    fechaIngreso:"24-08-2024", 
                    origenAtencion:'Dolor',
                    tipoConcepto:'Dolor',
                    cups:'3277',
                    nombreProcedimiento:'Urgencias',
                    cantidad: 10,
                    fechaOrden: '24-08-2024',
                    observaciones: 'Datos de observacion'
                },
];

export default Data;